console.log(                                                                                                                                                                                                                                                                                                                                                                                                       
"HHHHHHHHH     HHHHHHHHH  iiii                                                HHHHHHHHH     HHHHHHHHH                                                           iiii                                       \n"+
"H:::::::H     H:::::::H i::::i                                               H:::::::H     H:::::::H                                                          i::::i                                      \n"+
"H:::::::H     H:::::::H  iiii                                                H:::::::H     H:::::::H                                                           iiii                                       \n"+
"HH::::::H     H::::::HH                                                      HH::::::H     H::::::HH                                                                                                      \n"+
"  H:::::H     H:::::H  iiiiiiivvvvvvv           vvvvvvv eeeeeeeeeeee           H:::::H     H:::::H      eeeeeeeeeeee    rrrrr   rrrrrrrrr      ooooooooooo   iiiiiii     cccccccccccccccc    ssssssssss   \n"+
"  H:::::H     H:::::H  i:::::i v:::::v         v:::::vee::::::::::::ee         H:::::H     H:::::H    ee::::::::::::ee  r::::rrr:::::::::r   oo:::::::::::oo i:::::i   cc:::::::::::::::c  ss::::::::::s  \n"+
"  H::::::HHHHH::::::H   i::::i  v:::::v       v:::::ve::::::eeeee:::::ee       H::::::HHHHH::::::H   e::::::eeeee:::::eer:::::::::::::::::r o:::::::::::::::o i::::i  c:::::::::::::::::css:::::::::::::s \n"+
"  H:::::::::::::::::H   i::::i   v:::::v     v:::::ve::::::e     e:::::e       H:::::::::::::::::H  e::::::e     e:::::err::::::rrrrr::::::ro:::::ooooo:::::o i::::i c:::::::cccccc:::::cs::::::ssss:::::s\n"+
"  H:::::::::::::::::H   i::::i    v:::::v   v:::::v e:::::::eeeee::::::e       H:::::::::::::::::H  e:::::::eeeee::::::e r:::::r     r:::::ro::::o     o::::o i::::i c::::::c     ccccccc s:::::s  ssssss \n"+
"  H::::::HHHHH::::::H   i::::i     v:::::v v:::::v  e:::::::::::::::::e        H::::::HHHHH::::::H  e:::::::::::::::::e  r:::::r     rrrrrrro::::o     o::::o i::::i c:::::c                s::::::s      \n"+
"  H:::::H     H:::::H   i::::i      v:::::v:::::v   e::::::eeeeeeeeeee         H:::::H     H:::::H  e::::::eeeeeeeeeee   r:::::r            o::::o     o::::o i::::i c:::::c                   s::::::s   \n"+
"  H:::::H     H:::::H   i::::i       v:::::::::v    e:::::::e                  H:::::H     H:::::H  e:::::::e            r:::::r            o::::o     o::::o i::::i c::::::c     cccccccssssss   s:::::s \n"+
"HH::::::H     H::::::HHi::::::i       v:::::::v     e::::::::e               HH::::::H     H::::::HHe::::::::e           r:::::r            o:::::ooooo:::::oi::::::ic:::::::cccccc:::::cs:::::ssss::::::s\n"+
"H:::::::H     H:::::::Hi::::::i        v:::::v       e::::::::eeeeeeee       H:::::::H     H:::::::H e::::::::eeeeeeee   r:::::r            o:::::::::::::::oi::::::i c:::::::::::::::::cs::::::::::::::s \n"+
"H:::::::H     H:::::::Hi::::::i         v:::v         ee:::::::::::::e       H:::::::H     H:::::::H  ee:::::::::::::e   r:::::r             oo:::::::::::oo i::::::i  cc:::::::::::::::c s:::::::::::ss  \n"+
"HHHHHHHHH     HHHHHHHHHiiiiiiii          vvv            eeeeeeeeeeeeee       HHHHHHHHH     HHHHHHHHH    eeeeeeeeeeeeee   rrrrrrr               ooooooooooo   iiiiiiii    cccccccccccccccc  sssssssssss    \n"                                                                                                                                                                                                   )